version: "3.8"
services:
  etl:
    build: ./data
    container_name: etl_container
    volumes:
      - ./data:/app
      - ./data/logging/logs:/app/logging/logs
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - CONFIG_OBJECT_NAME=sources_config.json
      - CONFIG_POLL_INTERVAL=300
